spring:
  application:
    name: Welcome-API
  boot:
    admin:
      client:
        url: http://localhost:8080
server:
  port: 9092
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"